require "core.launch"
require "core.options"
require "core.keymaps"

spec "core.colorscheme"
spec "core.devicons"
spec "core.treesitter"
spec "core.mason"
spec "core.schemastore"
spec "core.lspconfig"
spec "core.whichkey"
spec "core.cmp"
spec "core.none-ls"
spec "core.mason-none-ls"

require "core.lazy"
