require "core.launch"
require "core.options"
require "core.keymaps"
require "core.autocmds"

-- Core plugins
spec "core.colorscheme"
spec "core.devicons"
spec "core.treesitter"
spec "core.mason"
spec "core.schemastore"
spec "core.lspconfig"
spec "core.whichkey"
spec "core.cmp"
spec "core.none-ls"
spec "core.mason-none-ls"
spec "core.telescope"
spec "core.project"
spec "core.nvimtree"
spec "core.comment"
spec "core.lualine"
spec "core.navic"
spec "core.breadcrumbs"
spec "core.harpoon"
spec "core.gitsigns"
spec "core.autopairs"
spec "core.indentline"
spec "core.lazygit"

-- Extras plugins
spec "core.extras.tabby"
spec "core.extras.neoscroll"
spec "core.extras.illuminate"
spec "core.extras.oil"
spec "core.extras.ufo"
spec "core.extras.lab"
spec "core.extras.fidget"

require "core.lazy"
